# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_title', models.CharField(db_index=True, max_length=100)),
                ('music_description', models.TextField(max_length=200)),
                ('music_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Genre.Genre')),
            ],
        ),
    ]
