# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
