# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(db_index=True, max_length=200)),
                ('desc', models.TextField(db_index=True, max_length=200)),
            ],
        ),
    ]
